AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
