module ActiveRecord::Originator
  interface _ArelVisitor
    def accept: (untyped, untyped) -> untyped
  end

  interface _Collector
    def <<: (String) -> self
    def add_bind: (untyped obj) -> self
    def add_binds: (untyped, ?untyped) -> self
    def value: () -> untyped
  end

  interface _Formatter
    def format: (String) -> String
  end
end
