module ActiveRecord
  module Originator
    module ArelVisitorExtension : _ArelVisitor
      TARGET_NODE_CLASSESS: Array[Symbol]
      def accept: (untyped object, _Collector collector) -> untyped

      private

      def originator_comment: (untyped o) -> String?

      def escape_comment: (String comment) -> String
    end
  end
end
