name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile}}
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - 'head'
        gemfile:
          - activerecord_6_0
          - activerecord_6_1
          - activerecord_7_0
          - activerecord_7_1
          - activerecord_7_2

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run bin/setup
      run: bin/setup
    - name: Run the default task
      run: bundle exec rake
